export enum ChannelsMain {
  browseFileSystem = 'browseFileSystem',
  createNewProject = 'createNewProject',
  getXtoryTemplates = 'getXtoryTemplates',
  getFileTypes = 'getFileTypes',
  openProject = 'openProject',
  openFileAsTab = 'openFileAsTab',
  fspExists = 'fspExists',
  fspMkdir = 'fspMkdir',
  fspWriteFile = 'fspWriteFile',
  fsMove = 'fsMove',
  fsRemove = 'fsRemove',
  revealPathInOS = 'revealPathInOS',
  customIPC = 'customIPC',
  logMessage = 'logMessage',
  selectImageFile = 'selectImageFile',
  importResource = 'importResource',
  getResources = 'getResources',
  updateResourceMetadata = 'updateResourceMetadata',
  removeResource = 'removeResource',
  getPluginConfig = 'getPluginConfig',
  updatePluginConfig = 'updatePluginConfig',
  updatePluginEnabled = 'updatePluginEnabled',
  restartApp = 'restartApp',
  getCharacters = 'getCharacters',
  createCharacter = 'createCharacter',
  updateCharacter = 'updateCharacter',
  removeCharacter = 'removeCharacter',
  getCharacterSettings = 'getCharacterSettings',
  updateCharacterSettings = 'updateCharacterSettings',
}

export enum ChannelsRenderer {
  addFileMenuItem = 'addFileMenuItem',
  broadcastLogMessage = 'broadcastLogMessage',
  toastMessage = 'toastMessage',
  onProjectOpened = 'onProjectOpened',
  onOpenFileAsTab = 'onOpenFileAsTab',
  onProjectTreeUpdated = 'onProjectTreeUpdated',
  onLoadPlugins = 'onLoadPlugins',
  onPluginsLoadingStart = 'onPluginsLoadingStart',
  onPluginsLoadingComplete = 'onPluginsLoadingComplete',
}
